import builtins
import google.protobuf.message
import typing

class SpamRequest(google.protobuf.message.Message):

    def __init__(self, *, eggs: builtins.str) -> None:...

    @builtins.property
    def eggs(self) -> builtins.str:...

    def HasField(self, field_name: typing.NoReturn) -> typing.NoReturn:...

    def WhichOneof(self, oneof_group: typing.NoReturn) -> typing.NoReturn:...

class SpamResponse(google.protobuf.message.Message):

    def __init__(self, *, banana: builtins.str) -> None:...

    @builtins.property
    def banana(self) -> builtins.str:...

    def HasField(self, field_name: typing.NoReturn) -> typing.NoReturn:...

    def WhichOneof(self, oneof_group: typing.NoReturn) -> typing.NoReturn:...