name: Check On Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  venv:
    uses: ./.github/workflows/setup.yaml

  lint:
    needs: venv
    uses: ./.github/workflows/setup.yaml
    with:
      fail-on-cache-miss: 'true'
    steps:
      - name: Show poetry env info
        run: poetry env info
      - name: Run mypy
        run: poetry run mypy
      - name: Run ruff check
        run: poetry run ruff check
      - name: Run ruff format
        run: poetry run ruff format --check

  test:
    needs: lint
    uses: ./.github/workflows/setup.yaml
    with:
      fail-on-cache-miss: 'true'
    steps:
      - name: Run pytest
        run: poetry run pytest --cov-report=xml
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON,PROTOC,BUF
