name: Check On Pull Request

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  venv:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        python-version: [ "3.9" ]
        protoc-version: [ "26.1" ]
        buf-version: [ "1.38.0" ]
    steps:
      - uses: ./.github/setup.yaml
        with:
          python-version: ${{ matrix.python-version }}
          protoc-version: ${{ matrix.protoc-version }}
          buf-version: ${{ matrix.buf-version }}

  lint:
    needs: venv
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        python-version: [ "3.9" ]
    steps:
      - uses: ./.github/setup.yaml
        with:
          python-version: ${{ matrix.python-version }}
          fail-on-cache-miss: 'true'
      - name: Show poetry env info
        run: poetry env info
      - name: Run mypy
        run: poetry run mypy
      - name: Run ruff check
        run: poetry run ruff check
      - name: Run ruff format
        run: poetry run ruff format --check

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        python-version: [ "3.9" ]
        protoc-version: [ "26.1" ]
        buf-version: [ "1.38.0" ]
    steps:
      - uses: ./.github/setup.yaml
        with:
          python-version: ${{ matrix.python-version }}
          protoc-version: ${{ matrix.protoc-version }}
          buf-version: ${{ matrix.buf-version }}
          fail-on-cache-miss: 'true'
      - name: Run pytest
        run: poetry run pytest --cov-report=xml
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON,PROTOC,BUF
