name: Check On Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
        protoc-version: [ "26.1" ]
        buf-version: [ "1.31.0" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # see details (matrix, python-version, python-version-file, etc.)
        # https://github.com/actions/setup-python
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install --all-extras
      - name: Install protoc
        run: |-
          wget -qO protoc.zip "https://github.com/protocolbuffers/protobuf/releases/download/v${{ matrix.protoc-version }}/protoc-${{ matrix.protoc-version }}-linux-x86_64.zip"
          && unzip -q protoc.zip 'bin/*' 'include/google/protobuf/*' -d .venv
      - name: Install buf
        run: |-
          wget -qO .venv/bin/buf "https://github.com/bufbuild/buf/releases/download/v${{ matrix.buf-version }}/buf-Linux-x86_64"
          && chmod +x .venv/bin/buf
      - name: Run mypy
        run: poetry run mypy
      - name: Run pytest
        run: poetry run pytest
      - name: Run ruff format
        run: poetry run ruff format --check
      - name: Run ruff format
        run: poetry run ruff format --check
